#!/bin/bash

echo "
Java Layer:
am      
appops   
appwidget
bmgr
bu     
content
dpm        
hid        
ime       
input      
media      
monkey
pm 
requestsync
settings
sm         
svc     
telecom 
uiautomator
wm

Native Layer:
dumpsys
screencap
vdc
ndc
debuggerd
atrace
"
