#!/system/bin/sh
set -x

#weixin
am start -n com.tencent.mm/.plugin.setting.ui.setting.SettingsFontUI
sleep 1
tap 980  2430
key-back

#weibo
am start -n com.sina.weibo/com.sina.weibo.FontSizeSettingActivity
sleep 1
tap 980 400
key-back
