#!/bin/bash

set -x

mkdir -p /run/resolvconf/

connectedVPN=`adb shell getprop sys.net.connectedVPN`

if [[ -z "$connectedVPN" ]]; then
  nameserver=`adb shell getprop net.dns1 | tr -d [:cntrl:]`
  echo nameserver $nameserver > /run/resolvconf/resolv.conf
  echo nameserver 223.5.5.5  >> /run/resolvconf/resolv.conf
  echo nameserver 223.6.6.6  >> /run/resolvconf/resolv.conf
else
  nameserver=`adb shell getprop net.dns1 | tr -d [:cntrl:]`
  echo nameserver $nameserver > /run/resolvconf/resolv.conf
  echo nameserver 223.5.5.5  >> /run/resolvconf/resolv.conf
  echo nameserver 8.8.4.4    >> /run/resolvconf/resolv.conf
fi 
